// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujxennrfkatyxgevlecb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqeGVubnJma2F0eXhnZXZsZWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDMxNjAsImV4cCI6MjA2MjM3OTE2MH0.Ftt-Er-gJDK_9J6uVFH5iwpoJKMKR-fACp-qp0I9cZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);